WebApplication3/Models/ErrorViewModel.cs
using System;

namespace WebApplication3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication3/Models/StateViewModel.cs
using System.Collections.Generic;

namespace WebApplication3.Models
{
    public class StateViewModel
    {
        public string State { get; set; }
        public List<string> Cities { get; set; }
    }

}

WebApplication3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication3/Controllers/StudentController.cs
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using WebApplication3.NewFolder;

namespace WebApplication3.Controllers
{
    public class StudentController :Controller
    {

        private static List<Registrants> studentList = new List<Registrants>();

        private static List<string> StateMaster = new List<string> { "UP", "UK", "TN", "MP", "HR" };
        private readonly Dictionary<string, List<string>> _stateCityData = new()
    {
        { "UP", new List<string> { "Lucknow", "Agra", "Varanasi", "Kanpur", "Meerut" } },
        { "UK", new List<string> { "Dehradun", "Nainital", "Haridwar", "Rishikesh", "Almora" } },
        { "TN", new List<string> { "Chennai", "Madurai", "Coimbatore", "Trichy", "Salem" } },
        { "MP", new List<string> { "Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain" } },
        { "HR", new List<string> { "Chandigarh", "Faridabad", "Gurugram", "Ambala", "Hisar" } }
    };


        public IActionResult Index()
        {
            return View();
        }
        public ActionResult Register()
        {
            ViewBag.States = _stateCityData.Keys;
            ViewBag.Cities = new List<string>();

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Registrants model)
        {
            if (ModelState.IsValid)
            {
                Random rand = new Random();
                int randomInt = rand.Next();
                model.Id = randomInt;
                studentList.Add(model);

                TempData["SuccessMessage"] = "Registration successful!";
                return RedirectToAction("List");
            }

            ViewBag.States = _stateCityData.Keys;
            ViewBag.Cities = new List<string> { "No cities available" };

            return View(model);
        }


        public ActionResult List()
        {
            return View(studentList);
        }

        public JsonResult GetCitiesByState(string state)
        {
             var cities = _stateCityData[state];

            return Json(cities);
        }


        public IActionResult Edit(int id)
        {
            ViewBag.States = _stateCityData.Keys;
            var student = studentList.FirstOrDefault(s => s.Id == id);

            if (student == null)
            {
                return NotFound();
            }
            ViewBag.Cities = _stateCityData[student.State];
            return View(student); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Registrants model)
        {
            var student = studentList.FirstOrDefault(s => s.Id == id);
            if (student == null)
            {

                return NotFound();
            }

            if (ModelState.IsValid)
            {
   
                    student.Name = model.Name;
                    student.Email = model.Email;
                    student.Mobile = model.Mobile;
                    student.State = model.State;
                    student.City = model.City;
                    student.AboutYourself = model.AboutYourself;
                    TempData["SuccessMessage"] = "Student updated successfully!";
                    return RedirectToAction("List");
            }
            ViewBag.States = _stateCityData.Keys;
            ViewBag.Cities = _stateCityData[student.State];

            return View(model); 
        }

        public ActionResult Delete(int id)
        {
            var student = studentList.FirstOrDefault(s => s.Id == id);
            if (student != null)
            {
                studentList.Remove(student);
                return RedirectToAction("List");
            }
            return NotFound();
        }

    }
}

WebApplication3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication3/Views/Student/Edit.cshtml
@model WebApplication3.NewFolder.Registrants

@{
    ViewBag.Title = "Edit Student";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["SuccessMessage"]
        </div>
    }
    <div style="display:flex;flex-direction:column;align-items:center">
        <div>
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name, "", new { style = "color:red;" })
        </div>

        <div>
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email, "", new { style = "color:red;" })
        </div>

        <div>
            @Html.LabelFor(m => m.Mobile)
            @Html.TextBoxFor(m => m.Mobile)
            @Html.ValidationMessageFor(m => m.Mobile, "", new { style = "color:red;" })
        </div>

        <div>
            @Html.LabelFor(m => m.State)
            @Html.DropDownListFor(m => m.State, new SelectList((IEnumerable<string>)ViewBag.States), "Select State", new { @class = "state-dropdown" })
            @* @Html.ValidationMessageFor(m => m.State) *@
            @Html.ValidationMessageFor(m => m.State, "", new { style = "color:red;" })
        </div>

        <div>
            @Html.LabelFor(m => m.City)
            @Html.DropDownListFor(m => m.City, new SelectList((List<string>)ViewBag.Cities), "Select City")
            @Html.ValidationMessageFor(m => m.City, "", new { style = "color:red;" })
        </div>

        <div>
            @Html.LabelFor(m => m.AboutYourself)
            @Html.TextAreaFor(m => m.AboutYourself)
            @Html.ValidationMessageFor(m => m.AboutYourself, "", new { style = "color:red;" })
        </div>

        <div>
            @Html.LabelFor(m => m.Photo)
            @Html.TextBoxFor(m => m.Photo, new { type = "file" })
            @Html.ValidationMessageFor(m => m.Photo, "", new { style = "color:red;" })
        </div>


        <div>
            <button class=" btn btn-primary" type="submit">Submit</button>
        </div>
    </div>
}

<a href="@Url.Action("List", "Student")">Back to Student List</a>

WebApplication3/Views/Student/List.cshtml
@model List<WebApplication3.NewFolder.Registrants>

@{
    ViewBag.Title = "Registered Students";
}

<h2>@ViewBag.Title</h2>
<a href="@Url.Action("Register", "Student")" class="btn btn-primary">Add New Student</a>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>State</th>
            <th>City</th>
            <th>About Yourself</th>
            <th>Photo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <td>@student.Name</td>
                <td>@student.Email</td>
                <td>@student.Mobile</td>
                <td>@student.State</td>
                <td>@student.City</td>
                <td>@student.AboutYourself</td>
                <td>


                </td>
                <td>

                    <a href="@Url.Action("Edit", "Student", new { Id = student.Id })" class="btn btn-warning">Edit</a>
                    @Html.ActionLink("Delete", "Delete", new { Id = student.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication3/Views/Student/Register.cshtml
@model WebApplication3.NewFolder.Registrants

@{
    ViewBag.Title = "Student Registration";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Register", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["SuccessMessage"]
        </div>
    }
    <div style="display:flex;flex-direction:column;align-items:center">
    <div >
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name)
        @Html.ValidationMessageFor(m => m.Name, "", new { style = "color:red;"})
    </div>

    <div>
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email)
        @Html.ValidationMessageFor(m => m.Email, "", new { style = "color:red;"})
    </div>

    <div>
        @Html.LabelFor(m => m.Mobile)
        @Html.TextBoxFor(m => m.Mobile)
        @Html.ValidationMessageFor(m => m.Mobile, "", new { style = "color:red;"})
    </div>

    <div>
        @Html.LabelFor(m => m.State)
        @Html.DropDownListFor(m => m.State, new SelectList((IEnumerable<string>)ViewBag.States), "Select State", new { @class = "state-dropdown" })
        @* @Html.ValidationMessageFor(m => m.State) *@
        @Html.ValidationMessageFor(m => m.State, "", new { style = "color:red;" })
    </div>

    <div>
        @Html.LabelFor(m => m.City)
        @Html.DropDownListFor(m => m.City, new SelectList((List<string>)ViewBag.Cities), "Select City")
        @Html.ValidationMessageFor(m => m.City , "", new { style = "color:red;"})
    </div>

    <div>
        @Html.LabelFor(m => m.AboutYourself)
        @Html.TextAreaFor(m => m.AboutYourself)
        @Html.ValidationMessageFor(m => m.AboutYourself, "", new { style = "color:red;"})
    </div>

    <div>
        @Html.LabelFor(m => m.Photo)
        @Html.TextBoxFor(m => m.Photo, new { type = "file" })
        @Html.ValidationMessageFor(m => m.Photo, "", new { style = "color:red;"})
    </div>


    <div>
            <button class=" btn btn-primary" type="submit">Submit</button>
    </div>
    </div>
        }


@section scripts {
    <script>
        $(".state-dropdown").change(function () {
            var selectedState = $(this).val();
            $.getJSON('@Url.Action("GetCitiesByState", "Student")', { state: selectedState }, function (data) {
                var cityDropdown = $("select[name='City']");
                cityDropdown.empty();
                $.each(data, function (index, value) {
                    cityDropdown.append('<option value="' + value + '">' + value + '</option>');
                });
            });
        });
    </script>
}